### ISSUE TITLE
Can't build miso or haskell-miso.org with nix-build

### ISSUE THREAD

**Issue by tysonzero** [dmjio/miso#349]
Running `nix-build` in the `miso` directory fails with output:

```
download-from-binary-cache.pl: could not download ‘http://hydra.nixos.org/nix-cache-info’ (Curl error 22)
fetching path ‘/nix/store/g3p47s65327d6j1qff6nfk3qjpnr5mfx-adjunctions-4.3’...
building path(s) ‘/nix/store/558czhwrzfzds3jfw6dzv0l91my9ay1l-source’

trying https://github.com/ptigwe/hs-flatris/archive/5b386e35db143205b4bd8d45cdf98423ed51b713.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0could not download ‘http://hydra.nixos.org/nix-cache-info’ (Curl error 22)

*** Downloading ‘http://cache.nixos.org/nar/0dayzrx71wsshy1vm47av2mxzzlkqqjlk13naf48n0pjwqsaab0v.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/g3p47s65327d6j1qff6nfk3qjpnr5mfx-adjunctions-4.3’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   159    0   159    0     0    159      0 --:--:-- --:--:-- --:--:--   239
100  189k  100  189k    0     0   189k      0  0:00:01 --:--:--  0:00:01  742k

fetching path ‘/nix/store/szzkj06q7kmcic5a5jcjwc45al33k87s-kan-extensions-5.0.2’...
100  8577  100  8577    0     0   8577      0  0:00:01  0:00:01 --:--:--  8577
unpacking source archive /private/tmp/nix-build-source.drv-0/5b386e35db143205b4bd8d45cdf98423ed51b713.tar.gz
output path ‘/nix/store/558czhwrzfzds3jfw6dzv0l91my9ay1l-source’ has r:sha256 hash ‘0wll5fizkdmj2hgd71v9klnnr6wxvvf36imchh2chm1slqm78zca’ when ‘1nsp5mlci20yacd8my04m30366a7gnshzx5nxziw6fs7fsirxadm’ was expected
killing process 42668
cannot build derivation ‘/nix/store/18kbkw0baq0rmr13x9rr7ww7pcxcsma8-cabal2nix-hs-flatris.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/18kbkw0baq0rmr13x9rr7ww7pcxcsma8-cabal2nix-hs-flatris.drv’ failed
(use ‘--show-trace’ to show detailed location information)
```

Similarly running `nix-build` in the `haskell-miso.org` directory fails with output:

```
...
configureFlags: --verbose --prefix=/nix/store/6m4n6macwakbzgip5l7n6d0jbwicchp6-cabal-install-2.0.0.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/sqnxl4phx3wq3i7vg8iny893ij21c9h1-cabal-install-2.0.0.1-doc/share/doc --with-gcc=clang --package-db=/private/tmp/nix-build-cabal-install-2.0.0.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --disable-tests --extra-include-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/include --extra-lib-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/lib
configureFlags: --verbose --prefix=/nix/store/q6zh2xcd8981yqds858ygp1d0z996kd2-haddock-api-2.18.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --datadir=/nix/store/prgrqz6hr5sj2194v8q6h93jr1ab70hw-haddock-api-2.18.1-data/share/ghc-8.0.2 --docdir=/nix/store/m38kyvd15l7b17a5ypwl3r8cyzk92ccj-haddock-api-2.18.1-doc/share/doc --with-gcc=clang --package-db=/private/tmp/nix-build-haddock-api-2.18.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --extra-include-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/include --extra-lib-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/lib
Setup: haddock-api.cabal: This package requires at least Cabal version 2.0
builder for ‘/nix/store/p8b0vwlccldmky9ainvbmmcvr4crslnw-haddock-api-2.18.1.drv’ failed with exit code 1
building path(s) ‘/nix/store/64qgn7cggw2j9b5nfw9fj2srcrhfdhbx-aeson-pretty-0.8.5-doc’, ‘/nix/store/sd5dh4klgr2vbb01ywashyq0kr7hh5kz-aeson-pretty-0.8.5’
building path(s) ‘/nix/store/1vi99k8iq6c10b2s2mkfp34lhhbnysqq-attoparsec-iso8601-1.0.0.0-doc’, ‘/nix/store/iv78x4kylqvz696gcc28yql13ac2dcd0-attoparsec-iso8601-1.0.0.0’
cannot build derivation ‘/nix/store/3j65ym8vljv1dc95y7x3bqgf2n7y9qnj-ghcjs-0.2.020170323.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/jqgqsmx39v5wqdysaj0cn0z1f2lr7y3v-http-date-0.0.6.1’, ‘/nix/store/n8v4vmpyyg3zymjbqaxg0041kla00ra9-http-date-0.0.6.1-doc’
cannot build derivation ‘/nix/store/xd3f01c3qh1y2pg91c59n40hrhwrc62f-haskell-miso-0.1.0.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/wkc56iplqy2zr34678dnigf36ngjx32w-haskell-miso.org.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/wkc56iplqy2zr34678dnigf36ngjx32w-haskell-miso.org.drv’ failed
```

I am using `OS X Yosemite 10.10.5`.

**Comment by dmjio** [comment]
@tysonzero thanks for reporting this. Fixed in 8d115ab0c04c3f5a41497a6a460b8cc1656a975d

**Comment by tysonzero** [comment]
Thanks! I'm still getting the same error when running `nix-build` within the `haskell-miso.org` directory.

**Comment by dmjio** [comment]
@tysonzero I can't reproduce this. Which error? What command are you using, `nixpkgs` is pinned, so it should be identical.

**Comment by tysonzero** [comment]
If I go to directory: `miso/examples/haskell-miso.org`

And run: `nix-build`

I get:

```
download-from-binary-cache.pl: could not download ‘http://hydra.nixos.org/nix-cache-info’ (Curl error 22)
these derivations will be built:
...
...
...
building path(s) ‘/nix/store/girl5q20w6kn22rp1r4bnryw8ab6563q-lucid-2.9.9-doc’, ‘/nix/store/jwwn1prjg83yyrh7pw8cy03a8dihms80-lucid-2.9.9’
building path(s) ‘/nix/store/6m4n6macwakbzgip5l7n6d0jbwicchp6-cabal-install-2.0.0.1’, ‘/nix/store/sqnxl4phx3wq3i7vg8iny893ij21c9h1-cabal-install-2.0.0.1-doc’
building path(s) ‘/nix/store/av9hcq9wdflr63hqdkcra17ah0sd2wjy-git-0.2.1’, ‘/nix/store/gvvf4lkbsflfirhlmhvciiavrbkhxn11-git-0.2.1-data’, ‘/nix/store/wxq9lx6zkhvpvzpvzrg0cycd7jc64p0m-git-0.2.1-doc’
building path(s) ‘/nix/store/m38kyvd15l7b17a5ypwl3r8cyzk92ccj-haddock-api-2.18.1-doc’, ‘/nix/store/prgrqz6hr5sj2194v8q6h93jr1ab70hw-haddock-api-2.18.1-data’, ‘/nix/store/q6zh2xcd8981yqds858ygp1d0z996kd2-haddock-api-2.18.1’
setupCompilerEnvironmentPhase
Build with /nix/store/5mzl841h6nxih2zvba7m0pp0cjhb63iq-ghc-8.0.2.
unpacking sources
unpacking source archive /nix/store/wwzrwl5frb498b1z5gn48199h0xxgnbl-lucid-2.9.9.tar.gz
setupCompilerEnvironmentPhase
setupCompilerEnvironmentPhase
Build with /nix/store/5mzl841h6nxih2zvba7m0pp0cjhb63iq-ghc-8.0.2.
source root is lucid-2.9.9
Build with /nix/store/5mzl841h6nxih2zvba7m0pp0cjhb63iq-ghc-8.0.2.
setupCompilerEnvironmentPhase
setting SOURCE_DATE_EPOCH to timestamp 1507135930 of file lucid-2.9.9/test/Main.hs
Build with /nix/store/5mzl841h6nxih2zvba7m0pp0cjhb63iq-ghc-8.0.2.
patching sources
compileBuildDriverPhase
setupCompileFlags: -package-db=/private/tmp/nix-build-lucid-2.9.9.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /private/tmp/nix-build-lucid-2.9.9.drv-0/Main.o )
Linking Setup ...
unpacking sources
unpacking source archive /nix/store/bsyhrs565czgd4l0pc3xiaan0brp3rm3-git-0.2.1.tar.gz
source root is git-0.2.1
setting SOURCE_DATE_EPOCH to timestamp 1513006981 of file git-0.2.1/git.cabal
unpacking sources
patching sources
unpacking source archive /nix/store/v502d5pw3kr5r17iwlwwdb478ycyvp12-cabal-install-2.0.0.1.tar.gz
compileBuildDriverPhase
setupCompileFlags: -package-db=/private/tmp/nix-build-git-0.2.1.drv-0/package.conf.d -j1 -threaded
source root is cabal-install-2.0.0.1
setting SOURCE_DATE_EPOCH to timestamp 1512181414 of file cabal-install-2.0.0.1/tests/README.md
patching sources
Replace Cabal file with edited version from http://hackage.haskell.org/package/cabal-install-2.0.0.1/revision/3.cabal.
compileBuildDriverPhase
[1 of 1] Compiling Main             ( Setup.hs, /private/tmp/nix-build-git-0.2.1.drv-0/Main.o )
setupCompileFlags: -package-db=/private/tmp/nix-build-cabal-install-2.0.0.1.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.hs, /private/tmp/nix-build-cabal-install-2.0.0.1.drv-0/Main.o )
Linking Setup ...
unpacking sources
unpacking source archive /nix/store/mz6gvy41vb2xlmiwyf5zscddbldjb15f-haddock-api-2.18.1.tar.gz
source root is haddock-api-2.18.1
setting SOURCE_DATE_EPOCH to timestamp 1500540397 of file haddock-api-2.18.1/test/Spec.hs
patching sources
Replace Cabal file with edited version from http://hackage.haskell.org/package/haddock-api-2.18.1/revision/1.cabal.
compileBuildDriverPhase
setupCompileFlags: -package-db=/private/tmp/nix-build-haddock-api-2.18.1.drv-0/package.conf.d -j1 -threaded
[1 of 1] Compiling Main             ( Setup.lhs, /private/tmp/nix-build-haddock-api-2.18.1.drv-0/Main.o )
Linking Setup ...
Linking Setup ...
configuring
configureFlags: --verbose --prefix=/nix/store/jwwn1prjg83yyrh7pw8cy03a8dihms80-lucid-2.9.9 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/girl5q20w6kn22rp1r4bnryw8ab6563q-lucid-2.9.9-doc/share/doc --with-gcc=clang --package-db=/private/tmp/nix-build-lucid-2.9.9.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --disable-tests --extra-include-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/include --extra-lib-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/lib
configuring
configureFlags: --verbose --prefix=/nix/store/av9hcq9wdflr63hqdkcra17ah0sd2wjy-git-0.2.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --datadir=/nix/store/gvvf4lkbsflfirhlmhvciiavrbkhxn11-git-0.2.1-data/share/ghc-8.0.2 --docdir=/nix/store/wxq9lx6zkhvpvzpvzrg0cycd7jc64p0m-git-0.2.1-doc/share/doc --with-gcc=clang --package-db=/private/tmp/nix-build-git-0.2.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --disable-tests --extra-include-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/include --extra-lib-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/lib
configuring
configureFlags: --verbose --prefix=/nix/store/6m4n6macwakbzgip5l7n6d0jbwicchp6-cabal-install-2.0.0.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --docdir=/nix/store/sqnxl4phx3wq3i7vg8iny893ij21c9h1-cabal-install-2.0.0.1-doc/share/doc --with-gcc=clang --package-db=/private/tmp/nix-build-cabal-install-2.0.0.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --disable-tests --extra-include-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/include --extra-lib-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/lib
Configuring lucid-2.9.9...
Dependency base >=4.5 && <5: using base-4.9.1.0
Dependency blaze-builder -any: using blaze-builder-0.4.0.2
Dependency bytestring -any: using bytestring-0.10.8.1
Dependency containers -any: using containers-0.5.7.1
Dependency hashable -any: using hashable-1.2.6.1
Dependency mmorph -any: using mmorph-1.1.0
Dependency mtl -any: using mtl-2.2.1
Dependency text -any: using text-1.2.2.2
Dependency transformers -any: using transformers-0.5.2.0
Dependency unordered-containers -any: using unordered-containers-0.2.8.0
configuring
configureFlags: --verbose --prefix=/nix/store/q6zh2xcd8981yqds858ygp1d0z996kd2-haddock-api-2.18.1 --libdir=$prefix/lib/$compiler --libsubdir=$pkgid --datadir=/nix/store/prgrqz6hr5sj2194v8q6h93jr1ab70hw-haddock-api-2.18.1-data/share/ghc-8.0.2 --docdir=/nix/store/m38kyvd15l7b17a5ypwl3r8cyzk92ccj-haddock-api-2.18.1-doc/share/doc --with-gcc=clang --package-db=/private/tmp/nix-build-haddock-api-2.18.1.drv-0/package.conf.d --ghc-option=-optl=-Wl,-headerpad_max_install_names --ghc-option=-j1 --disable-split-objs --disable-library-profiling --disable-profiling --enable-shared --disable-coverage --enable-library-vanilla --enable-executable-dynamic --enable-tests --extra-include-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/include --extra-lib-dirs=/nix/store/h7hipm2yxyzxaigms966rbm89m0qfny4-libc++-4.0.1/lib
Setup: haddock-api.cabal: This package requires at least Cabal version 2.0
builder for ‘/nix/store/p8b0vwlccldmky9ainvbmmcvr4crslnw-haddock-api-2.18.1.drv’ failed with exit code 1
building path(s) ‘/nix/store/64qgn7cggw2j9b5nfw9fj2srcrhfdhbx-aeson-pretty-0.8.5-doc’, ‘/nix/store/sd5dh4klgr2vbb01ywashyq0kr7hh5kz-aeson-pretty-0.8.5’
building path(s) ‘/nix/store/1vi99k8iq6c10b2s2mkfp34lhhbnysqq-attoparsec-iso8601-1.0.0.0-doc’, ‘/nix/store/iv78x4kylqvz696gcc28yql13ac2dcd0-attoparsec-iso8601-1.0.0.0’
cannot build derivation ‘/nix/store/3j65ym8vljv1dc95y7x3bqgf2n7y9qnj-ghcjs-0.2.020170323.drv’: 1 dependencies couldn't be built
building path(s) ‘/nix/store/jqgqsmx39v5wqdysaj0cn0z1f2lr7y3v-http-date-0.0.6.1’, ‘/nix/store/n8v4vmpyyg3zymjbqaxg0041kla00ra9-http-date-0.0.6.1-doc’
cannot build derivation ‘/nix/store/8694brcywkn8iys8alhliz0g6772j97g-haskell-miso-0.1.0.0.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/a957nazj75rh59slvpxb84kp29bh1vwm-haskell-miso.org.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/a957nazj75rh59slvpxb84kp29bh1vwm-haskell-miso.org.drv’ failed
```

**Comment by dmjio** [comment]
Ah, `nixpkgs` is not pinned.

default `pkgs` to this:

```nix
{ pkgs ? import ((import <nixpkgs> {}).fetchFromGitHub {
    owner = "NixOS";
    repo = "nixpkgs";
    rev = "a0aeb23";
    sha256 = "04dgg0f2839c1kvlhc45hcksmjzr8a22q1bgfnrx71935ilxl33d";
  }){}
}
```

**Comment by tysonzero** [comment]
That worked! Thanks! It might be worth adding that to `miso/examples/haskell-miso.org/default.nix`.

**Comment by dmjio** [comment]
Great! Will do.
