### ISSUE TITLE
Consider getting rid of all non-internal non-prelude wildcard imports

### ISSUE THREAD

**Issue by tysonzero** [dmjio/miso#413]
Quite a few versions of miso break in various circumstances due to function names in imports colliding with functions defined within the module. These errors usually get fixed relatively quickly but it still leads to versions of miso being pushed that are essentially broken for a large portion of users. E.g `0.19.0.0` is broken for anyone using `nix` and up to date dependencies.

I think it is worthwhile to go through and make all third party library imports explicit. If others agree I am happy to do this myself whenever I next have time.

**Comment by dmjio** [comment]
Can you give me an example of breakage with nix and `0.19`, I am on `nixpkgs-unstable` and cannot reproduce.

**Comment by dmjio** [comment]
Is that that the only issue? Seems fixed now.

**Comment by tysonzero** [comment]
Right, you guys are doing a good job of fixing these issues when they come, but that fix comes AFTER the `0.19.0.0` release, so the most up to date hackage version is still broken. If going forward we use explicit (or qualified when desired) imports, and do a one time conversion now, then this issue will completely stop occurring.

**Comment by dmjio** [comment]
I'll release `0.20.0.0` and deprecate `0.19.0.0` if that will help.

**Comment by tysonzero** [comment]
Releasing 0.20.0.0 would be great, thanks! Probably don't need to deprecate 0.19.0.0 since it's a purely compile time error that for many won't occur.

I was just thinking that for future safety it would be good to go with explicit imports.
