### ISSUE TITLE
Servant.API.Generic example?

### ISSUE THREAD

**Issue by patrickmn** [dmjio/miso#518]
Can't quite figure out how to `runRoute` a generic record.

https://haskell-servant.readthedocs.io/en/stable/cookbook/generic/Generic.html

Seems like I need an AsRouteT?

**Comment by dmjio** [comment]
Seems like you might need:

api :: Proxy (ToServantApi Routes)
api = genericApi (Proxy :: Proxy Routes)

You’d probably have to further apply miso’s type family to the result of ToServantAPI.

**Comment by patrickmn** [comment]
That does seem to work, but I'm struggling with converting a corresponding record of `model -> View action` handlers, i.e. what you'd use `AsServer` and `genericServe` with Wai.

```haskell
handlers :: Routes AsRoute  -- <-- What should this be?
handlers = Routes
  { _rAbout = \m -> text "about"
  , ...
  }
```

From Servant:

```haskell
-- | A type that specifies that an API record contains a server implementation.
data AsServerT (m :: * -> *)
instance GenericMode (AsServerT m) where
    type AsServerT m :- api = ServerT api m

type AsServer = AsServerT Handler
```

**Comment by dmjio** [comment]
I'd try this type family http://hackage.haskell.org/package/miso-1.2.0.0/docs/Miso-TypeLevel.html
`ToServerRoutes`.

**Comment by dmjio** [comment]
And here's an example of its usage:
https://github.com/dmjio/miso/blob/master/examples/haskell-miso.org/server/Main.hs#L53

**Comment by patrickmn** [comment]
I appreciate the examples, but I guess I don't understand type families well enough to figure out how to convert the (value-level) record of handlers to a tree of :<|> handlers.

**Comment by dmjio** [comment]
It should be simply calling `pure` to get `View Action` to be `Handler (View Action)`, where `Handler ~ ExceptT String IO`, but I've never used this with the generic record mechanism. They might require pure to be used inside of the generic traversal.

**Comment by patrickmn** [comment]
I think I see how the conversion to server handlers happen, as you say. But I want to use the record to route client-side using `Miso.Router.runRoute`. How do I define `handlers :: Routes _` such that rather than becoming `ServerT api m` (`Routes AsServer`) it becomes `RouteT api a`?

I tried

```haskell
data AsRouteT (m :: * -> *)
instance GenericMode (AsRouteT m) where
    type AsRouteT m :- api = RouteT api m
```

which leads to

```
   • Expecting one more argument to ‘m’
      Expected a type, but ‘m’ has kind ‘* -> *’
    • In the second argument of ‘RouteT’, namely ‘m’
      In the type ‘RouteT api m’
      In the type instance declaration for ‘:-’
    |
149 |     type AsRouteT m :- api = RouteT api m
    |                                         ^
```

That makes sense since the type signature of `ServerT` is `ServerT api (m :: * -> *) :: *`, but this is the point at which I'm reminded to revisit the typeclassopedia.

**Comment by dmjio** [comment]
Can you past me a full minimal example and I can check it out tonight.

**Comment by patrickmn** [comment]
Yep, will do in a bit.

**Comment by patrickmn** [comment]
I'm now having some unrelated GHCJS build problem where `cabal new-build --ghcjs` (in reflex-platform shell) can't deduce ToJSVal Value when building Miso as a dependency for my sample project: https://gist.github.com/patrickmn/31ec098a4eacc23d773aa71f29b2c612. IIRC I've seen this before but I can't remember why, so for the moment I can't build the jsexe for the example below. (I really hate Haskell build tooling sometimes -- I wish snack was fast on large projects!)

But:
  - Clone and `new-run` this: https://github.com/patrickmn/miso-generic-example/
  - Uncomment the problematic section here: https://github.com/patrickmn/miso-generic-example/blob/master/src/Miso/Generic/Example/Types.hs#L80-L103
  - Demo of how generic servant handlers are made and served: https://github.com/patrickmn/miso-generic-example/blob/master/ghc-src/Miso/Generic/Example/Server.hs

Hope this is enough to go on :)

**Comment by patrickmn** [comment]
Fixed the GHCJS build issue and the example client.

**Comment by dmjio** [comment]
@patrickmnc miso comes with an up-to-date `nixpkgs` set that should suffice. Still getting to this.

**Comment by patrickmn** [comment]
No rush, consider it a feature request :) I find Servant insufferable without the record syntax, but I can deal for now.

**Comment by dmjio** [comment]
This should be a full example of integrating miso with `Servant.API.Generic`.

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeApplications #-}

module Test where

import Miso
import Network.URI         (URI(..))
import Servant.API.Generic
import Servant
import GHC.TypeLits

-- `miso` function gives pre-rendering
-- main :: IO ()
-- main = do
--   mvar <- newMVar (0 :: Int) -- some impure type like MVar, etc.
--   miso $ \uri ->
--     startApp { view = viewModel (Model uri)
--              , update = updateModel mvar -- keeps Model pure by making it arg to `updateModel`
--              , subs = []
--              , events = defaultEvents
--              , initialAction = NoOp
--              }

-- | View, dispatches to fields in 'Route'
viewModel :: Model -> View Action
viewModel m =
  case runRoute clientApi clientRoutes getUri m of
    Left _ -> div_ [] [ "404" ]
    Right v -> v

clientApi :: Proxy (ToServantApi Routes)
clientApi = genericApi (Proxy @ Routes)

clientRoutes :: ToServant Routes AsView
clientRoutes = toServant routeViews

data Model
  = Model
  { getUri :: URI
  -- ^ URI present on Model
  } deriving (Eq)
  -- ^ Side note: 
  -- If we can keep the Eq instance on Model (move `MVar` to update function) it'd be a perf win I believe.
  -- instance Eq Model where _ == _ = False, will diff on all changes. So things like scroll events
  -- will become untenable.

data Action
  = ChangeURI URI
  | NoOp

data Routes route
  = Routes
  { _rMain :: route :- "hey" :> QueryParam "ok" Int :> View Action
  , _rHome :: route :- View Action
  } deriving (Generic)

data AsView

-- This is something we need to have in order to `runRoute`.
instance GenericMode AsView where
  type AsView :- xs = GenView xs

type family GenView as :: * where
  GenView (Capture name x :> xs) = x -> GenView xs
  GenView (QueryParam name x :> xs) = Maybe x -> GenView xs
  GenView (QueryParams name x :> xs) = [x] -> GenView xs
  GenView (CaptureAll name x :> xs) = [x] -> GenView xs
  GenView ((x :: Symbol) :> xs) = GenView xs -- we strip out `Symbol` to get kind '*', so View can inhabit
  GenView (View a) = Model -> View a

routeViews :: Routes AsView
routeViews =
  Routes
  { _rMain = \qParam model ->
      div_
      [ onClick $ ChangeURI $ linkURI $ fieldLink _rMain qParam
      ]
      [ "main"
      ]
  , _rHome = \model ->
      div_
      [ onClick $ ChangeURI $ linkURI $ fieldLink _rHome
      ]
      [ "home"
      ]
  }
```
